#!/bin/bash

# # #
# Default path to fastconfig
CONFIG_FASTCONFIG_INI="$(pwd)/fastconfig.ini"
CONFIG_DIRECTORY="$(pwd)/config"
CONFIG_SOURCE_DIR="$(pwd)/source"


# # #
# Return all rows from PROJECT section fastconfig.ini
function getProjects()
{
  awk '
BEGIN {
  FS="="
  section=""
}
{
  if(match($1, /^\[[a-zA-Z0-9\_]+\]$/))
  {
    print $1
  }

}
' $CONFIG_FASTCONFIG_INI
}

# # #
# Return count PROJECT section fastconfig.ini
function getProjectsCount()
{
  echo "$(getProjects | wc -l | awk '{print $1}')"
}

# # #
# Check path for it identity file or directory
# 1 - it's file
# 2 - it's directory
# 0 - not exist or other
function checkIsFileOrDirectory()
{
  if [[ -f $1 ]]; then
    echo 1
  elif [[ -d $1 ]]; then
    echo 2
  else
    echo 0
  fi
}

# # #
# Copy project source file from your project
function copyProjectSourceFiles()
{
  echo In $CONFIG_FASTCONFIG_INI finded "$(getProjectsCount)" projects
  echo Check files and copy:

  COUNT=0

  getProjects | while read -r line
  do
    ((COUNT++))

    LOCAL_PROJECT="$(echo "$line" | awk 'BEGIN{FS="="}{print $1}')"
    LOCAL_PROJECT_PATH="$(echo "$line" | awk 'BEGIN{FS="="}{print $2}')"
    LOCAL_SOURCE_CONFIG_PATH="${CONFIG_SOURCE_DIR}/${LOCAL_PROJECT}/"

    printf "%d. Project: %s\t %s\n" $COUNT "$LOCAL_PROJECT" "$LOCAL_PROJECT_PATH"

    if [[ 0 == $(checkIsFileOrDirectory "$CONFIG_SOURCE_DIR") ]]; then
      mkdir "$CONFIG_SOURCE_DIR"
    fi

    if [[ 0 != $(checkIsFileOrDirectory "$LOCAL_PROJECT_PATH") ]]; then
      if [[ 0 == $(checkIsFileOrDirectory "$LOCAL_SOURCE_CONFIG_PATH") ]]; then
        mkdir "$LOCAL_SOURCE_CONFIG_PATH"
      fi

      cp "$LOCAL_PROJECT_PATH" "$LOCAL_SOURCE_CONFIG_PATH"
    fi
  done
}

# # #
# Create config from file how placed in source
function createConfigFromSource()
{
  if [[ 0 == $(checkIsFileOrDirectory "$CONFIG_DIRECTORY") ]]; then
    mkdir "$CONFIG_DIRECTORY"
  fi
}

# # #
# Get filename from file
function getSourceFileName() {
  if [[ -n "$1" ]]; then
     getProjects | awk -v project="$1" 'BEGIN {FS="="} {if($1 == project){print substr($2, match($2, /[^\/]+$/), RLENGTH)}}'
  fi
}

# # #
# Find alias fastconfig.ini
function findAlias()
{
  awk '
BEGIN {
  FS="="
}
{
  print substr($1, match($1, /[^\[].*[^\]]/), RLENGTH)
}
' $CONFIG_FASTCONFIG_INI
}

# # #
# add alias to config
function addAlias()
{
  alias="[$1]"
  aliasWithoutBrackets="$1"

  # check STDIN alias
  if [[ -n "$1" && $(printf "%s" "$alias" | awk '/^.+$/{print match($1, /[a-zA-Z0-9\_]+/)}') -gt 0 ]]; then
    DIRECTORY_WITH_ALIAS="${CONFIG_DIRECTORY}/${alias}"

    # Create config directory if not exists
    if [[ 0 == $(checkIsFileOrDirectory "$CONFIG_DIRECTORY") ]]; then
      mkdir $CONFIG_DIRECTORY
    fi

    # create config file
    if [[ 0 == $(checkIsFileOrDirectory "$CONFIG_FASTCONFIG_INI") ]]; then
      touch "$CONFIG_FASTCONFIG_INI"
    fi

    isAliasExist=$(awk -v alias="$alias" '
    BEGIN {
      FS="="
      isFinded=0
    }
    {
      configAlias=substr($1, match($1, /^\[[a-zA-Z0-9\_]+\]$/), RLENGTH)

      if (configAlias == alias)
      {
        isFinded=1
        exit 1
      }
    }
    END {
      print isFinded
    }
    ' "$CONFIG_FASTCONFIG_INI")

    if [[ 1 == "$isAliasExist" ]]; then
      echo "Alias $aliasWithoutBrackets already exist"
    else
      echo "$alias" >> "$CONFIG_FASTCONFIG_INI"
      echo "root = path/to/project" >> "$CONFIG_FASTCONFIG_INI"
      echo "source_file = path/to/config.php" >> "$CONFIG_FASTCONFIG_INI"
      echo "output_file = path/to/config.php" >> "$CONFIG_FASTCONFIG_INI"
      echo "output_file_name = output_file_name" >> "$CONFIG_FASTCONFIG_INI"
      echo "" >> "$CONFIG_FASTCONFIG_INI"
      echo "Alias $aliasWithoutBrackets has added"
    fi

  else
    echo "Your need write alias name"
  fi
}

# # #
# Get list of commands
function getHelp()
{
  echo "FastConfig "
  echo "How to use [argument] [additional option]. For example -a my_alias"
  echo ""
  echo "    +--------------------------------------------------------+"
  echo "    |                   TABLE OF COMMANDS                    |"
  echo "    +----+------------+--------------------------------------+"
  echo "    | -h | --help     | list all commands                    |"
  echo "    +----+------------+--------------------------------------+"
  echo "    | -a | --add      | add new aliast to fastconfig.ini     |"
  echo "    +----+------------+--------------------------------------+"
  echo "    | -s | --switch   | switch config by alias               |"
  echo "    +----+------------+--------------------------------------+"
  echo "    | -l | --list     | print list exist aliases             |"
  echo "    +----+------------+--------------------------------------+"
}


#getSourceFileName panel
#createConfigFromSource
#copyProjectSourceFiles

case $1 in
  "-a" | "--add")
    addAlias "$2"
    ;;
  "-l" | "--list")
    getProjects | sed 's/^\[\(.*\)\]$/\1/'
    ;;
  * )
    getHelp
    ;;
esac
