#!/bin/bash

echo "Created By Vladsislav Pototskiy [@echoladone]. June 2020"
echo "Hello, it's fastconfig tool, how help generate local-config files for your Yii2 project"

CONFIG_DIR="$(pwd)/configs/"
CONFIG_FASTCONFIG_INI="$(pwd)/fastconfig.ini"

function writeOk() {
  echo " \e[32mOK!\033[0m"
}

function writeTFI() {
  printf "$1\n" >>$CONFIG_FASTCONFIG_INI
}

function createFastconfigIni() {
  touch $CONFIG_FASTCONFIG_INI
  writeTFI "[FASTCONFIG]"
  writeTFI "source_config: /PATH/TO/SOURCE/CONFIG/FILE.php"
}

function checkFastconfigIni() {
  printf "Check fastconfig.ini"

  if [[ ! -d "$CONFIG_FASTCONFIG_INI" ]]; then
    echo "You are not having $CONFIG_FASTCONFIG_INI."
    printf "You are want to create fastconfig.ini [Y/n]: "

    read answer
    if [[ "$answer" != "${answer[Yy]}" || -z "$answer" ]]; then
      checkFastconfigIni
    fi
  else
    writeOk
  fi
}


#if [[ ! -d "$CONFIG_DIR" ]]; then
#  echo "You are not having $CONFIG_DIR"
#  echo "You are need initialize default configs for fastconfig. Right now process initialize be started"
#  printf "You are sure [y/N]: "
#  read answer
#
#  if [[ "$answer" != "${answer#[Yy]}" ]]; then
#    printf "Creating directory ${CONFIG_DIR}..."
#    mkdir $CONFIG_DIR
#    writeOk
#
#    printf "Check fastconfig.ini"
#
#    if [[ ! -f "$CONFIG_FASTCONFIG_INI" ]]; then
#        createFastconfigIni
#    fi
#
#
#  else
#    echo "Program is terminated with code 0"
#  fi
#fi

#printf "Yes(y)/No(n): "
#
#read promtCreateLocalDefault
#
## ---- BLOCK CREATE DEFAULT CONFIG -----
#declare -l promtCreateLocalDefault
#promtCreateLocalDefault=$promtCreateLocalDefault
#
#if [[ "$promtCreateLocalDefault" == "yes" || "$promtCreateLocalDefault" == "y" ]]; then
#  echo "$promtCreateLocalDefault"
#fi
